s3:
  index: "index.html"
  error: "error.html"
  redirects:
    - path: /sections
      destination: https://cs50.harvard.edu/college/2023/fall/sections/
    - path: /mindmap
      destination: https://coggle.it/diagram/ZpwngWw-U5VzXCQY/t/cs50/4e7f89627c4b87a6906f2184e3c5e100e2bbdc36ade796aeb39d62e314214ad2
    - path: /classrooms
      destination: https://docs.google.com/spreadsheets/d/1L0u2MvJmxVAy7euXSq7b861Wuc-1kb7nsuNULAbCAaM/edit?usp=sharing
    - path: /remix
      destination: https://drive.google.com/drive/folders/1c7C1r2DDc4cuQUqJudR7wf6HoEKMiorW?usp=sharing
    - path: /nextech
      destination: https://drive.google.com/drive/folders/1wtQl2G1Rvmu3iBQwUceGKFxICNZKkSSQ?usp=drive_link
    - path: /emerging-pedagogies
      destination: https://carterzenke.me/workshops/2024/fall/emerging-pedagogies/Generative-AI-and-Pedagogical-Innovation.pdf
    - path: /ap-csp-exam
      destination: https://apcentral.collegeboard.org/media/pdf/ap-computer-science-principles-course-and-exam-description.pdf
