s3:
  index: "index.html"
  error: "error.html"
  redirects:
    - path: /sections
      destination: https://cs50.harvard.edu/college/2023/fall/sections/
    - path: /ncboe
      destination: https://youtu.be/nVjMOChUFyY?t=4996