services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
    command: >
      sh -c 'bundle install &&
      bundle exec jekyll serve --livereload --host 0.0.0.0'
    ports:
      - 4000:4000
