services:
  jekyll:
    image: jekyll/builder:latest
    volumes:
      - ./:/srv/jekyll
    command: sh -c 'bundle install && bundle exec jekyll serve --watch --host 0.0.0.0'
    ports:
      - 4000:4000
